services:
  backend:
    build: ./backend
    container_name: cs2-manager-api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/database.sqlite:/app/database.sqlite
      - ./backend/.env:/app/.env
      - /home/steam/cs2_data:/app/cs2_data # <--- AJOUTE CETTE LIGNE
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env