services:
  backend:
    build: ./backend
    container_name: cs2-manager-api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Pour piloter Docker
      - ./backend:/app # Pour ne pas perdre tes données SQLite
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env